### PR TITLE
Remove Squash action

### PR DESCRIPTION
**Pull request by MrEnigmamgine**
MM 155, Hill giant does not have squash action.

### CODE REVIEW

**Comment by ThaBullfrog** [comment]
It's from Storm Kings Thunder

**Comment by chisaipete** [comment]
What's the opinion, should we leave the Squash action?  Does it change the effective CR of the monster?

**Comment by ThaBullfrog** [comment]
Leave it. It's not like this project it core only, and Storm King's Thunder is an official WotC adventure. It does not change the CR.

**Comment by chisaipete** [comment]
Closing, please reopen if you have a strong argument otherwise.

**Pull request closed without merging**
