### PR TITLE
Added Sort by (name or CR)

### PR DESCRIPTION
**Pull request by thisboyiscrazy**
Should solve Issue #9

### CODE REVIEW

**Comment by chisaipete** [comment]
Sorry, I didn't get around to looking at this until now.  I think something is wonky with the "Back to top ^" links, they seem to be in the wrong spot relative to the indexes.

image

compare to:

image

**Comment by thisboyiscrazy** [comment]
Shoud be corrected

**Comment by chisaipete** [comment]
Looks good, I'll merge and publish this update.  How hard would it be to add sorting by name to each of the monster type pages as well? (Giants, Fiends, Monstrosities, etc)

**Comment by thisboyiscrazy** [comment]
I thought about that to I will look into it.

**Comment by chisaipete** [comment]
OH, it looks like the site is busted now when you click sort by name.  Do you see that too?

**Comment by chisaipete** [comment]
I think it has to do with the URL writing. I'm looking at it now unless you want to

**Comment by thisboyiscrazy** [comment]
I'll take a look.

**Comment by chisaipete** [comment]
I think I have the fix, I'm testing now.

**Comment by chisaipete** [comment]
it's now fixed in 0431a977da893580607ef48be7eafcb8afc2ae17

**Pull request merged**
