### PR TITLE
Displacer Beast

### PR DESCRIPTION
**Pull request by thisboyiscrazy**

### CODE REVIEW

**Comment by chisaipete** [comment]
Hmm, this looks like it pretty heavily breaks the bestiary as published, are you sure you meant to submit a pull request?

**Comment by thisboyiscrazy** [comment]
Interesting, what broke I will fix it?

**Comment by chisaipete** [comment]
Look at the list of files you pushed in the commit, none of them are the Displacer Beast! They are all auto-generated GitHub pages.  When I run 'rake generator's and then try to view the source in my browser it pulls up a generic GitHub template.

**Comment by thisboyiscrazy** [comment]
Oh, wow I must have messed that up, I was trying to preview what i was doing.

I will close the PR and re add the Displacer Beast.

**Pull request closed without merging**
