### PR TITLE
MToF all monsters

### PR DESCRIPTION
**Pull request by MrEnigmamgine**
A few things of important note:
There are three files that aren't creatures, but instead describe the traits that can be applied to other monsters. these files are named <thing>template and the 'template' tag has been put in the tags section.

There are also some dwarves that were in the file that I parsed.  As far as I know these aren't officially in any book so I added the tag 'unofficial'.  I didn't want to strip them out because they looked useful.

Lastly, there were some quirks during the parsing and I've gone through and cleaned it up.  It's possible I missed something so not all of the files are guaranteed to be perfect.

### CODE REVIEW

**Comment by chisaipete** [comment]
So, I've just finally looked at this.  You need to reformat the post names to have dates in them in order for the Jekyll parser to work properly.  There may be other issues, but that's the biggest one.

**Comment by Kyrremann** [comment]
The name issue will be solved by my PR, then we just need to merge them into the `_creatures` folder, and strip out the `date`-field.

**Comment by MrEnigmamgine** [comment]
Oh that would be helpful.. I was worried about it because I'm not sure how to go about renaming all these files.

**Comment by Kyrremann** [comment]
We'll also see if we bother to add the space/- in the filename.

But, are these files generated from a tool or something, or are they handwritten? I'm just curious.

**Comment by MrEnigmamgine** [comment]
I learned some python to make a script to parse some xml and loop through the object tree and print it to a file since everything was in a predictable pattern.

I'm not sure how to go about writing a script to rename because I have to account for all of the possible dates that might be in the string... otherwise I'll just wind up making duplicates or failing in some other miserable fashion.

**Comment by Kyrremann** [comment]
Ah, that's pretty clever.

**Comment by chisaipete** [comment]
@Kyrremann what order do you want between these two PRs (#57 and #53 ) adding and correcting creatures and yours (#59)?

**Comment by Kyrremann** [comment]
If you merge both #57 and #53 to master, I can then merge them into #59 and update them. After that I can create a PR for #7 .

**Pull request merged**
