### PR TITLE
Statblock

### LINKED ISSUE #7: Explore using webcomponents to look like a stat block
http://valloric.github.io/statblock5e/

:)

### PR DESCRIPTION
**Pull request by Kyrremann**
Fixes #7 

@chisaipete please take a look.

### CODE REVIEW

**Comment by chisaipete** [comment]
Does github rate limit the generation of sites?  I notice that this takes a non-trivial amount of time to generate each page when I build on my i7-8850 with 16GB of RAM.

**Comment by Kyrremann** [comment]
I've noticed that too. It helps to use the `-i` argument, so you don't have to build every page if you make some changes. But yes, on my Macbook pro it takes about 90s the first time.

It doesn't look like it's rate limited. https://help.github.com/en/articles/what-is-github-pages

I can merge it in to my master, and try it there?

**Comment by chisaipete** [comment]
I'm also trying to decide on a design thing...does the green now clash with the statblock?  Should we re-theme the site?  Maybe the same vomit-like orange color of the top and bottom bars of the statblock?  

Also, I'm not sure I'm happy with the tags.  Can we make the appropriate fields in the block clickable as well--then possibly make the tags look more like little buttons without the tags callout?  Something like: 
image Ignore the environment thing, but just a little all caps word with a simple box around it I think would look nice.

**Comment by chisaipete** [comment]
> I can merge it in to my master, and try it there?

Let's not stress over it until it breaks :)

**Comment by chisaipete** [comment]
One more design point: Can you match the same font text used for the rest of the site in the title of the block?  It looks off to have so many fonts mixed in there. Especially with the Small caps. Unless  you have a different opinion :)

**Comment by chisaipete** [comment]
Another thought....sorry. Is there support for double-wide blocks?  I.e. the Terrasque looks nice on a phone or narrow screen, but would be more helpful on a tablet or computer in a landscape format.  Also, can the tall statblock be centered on the page?

**Comment by Kyrremann** [comment]
No worries with the feedback, bring it on ;) 

I'll try with a different main color, it may work with the orange. 

Agree with the tags. I'll look into trying to match what you linked. 

True about the fonts, too many fonts are never good. So you want to use the font from statblock, or use the one already in use on the site? 

Double-wide would be hard, but it may be doable. I'll give it a shot tonight, or tomorrow.

**Comment by chisaipete** [comment]
Double wide is more of a stretch goal. If we can get the tall block
centered in the widescreen view, that would be good enough for release.

I like the font used on the site better than the statblock font.

**Comment by Kyrremann** [comment]
Site-font
image

Statblock-font
image


Site-font looks better in the image I think, then on my Mac :p

**Comment by Kyrremann** [comment]
Fixed tags, but should probably change some more?

image

Maybe move them inside the stablock-box?

**Comment by Kyrremann** [comment]
Please review the new changes and let me know what you think.

**Comment by chisaipete** [comment]
I think from a design standpoint, I like the new font.  It MIGHT be less readable, but I do like how it looks now.

I don't see the tag blocks in the version I pulled.  I like what you have, but would prefer the color of the link to be black/matching the button border.  What does it look like when you have a bunch of tags inside the statblock?  I think it would be cool to have them in the bottom of the block.

Also, any luck on centering the Statblock on the page?

image

**Comment by Kyrremann** [comment]
Forgot the centereing, I can push that next.

Also didn't push the tags as I wanted your review of the image first. I'll fix the link colour and then push that.

**Comment by chisaipete** [comment]
It looks like the Capitalization is a bit busted for multi-word creature names:

image
image

**Comment by chisaipete** [comment]
This isn't necessarily a topic for this PR, but shall I create a new issue for removing empty categories when clicking on tags?

image

**Comment by Kyrremann** [comment]
Have thought about that too, and yeah, make a new PR.

**Comment by chisaipete** [comment]
I just found this color which is complimentary to the vomit color and makes the site look more plesant. In main.scss:
$brand-color-secondary: #109269;

image

**Comment by Kyrremann** [comment]
The green colour should have been fixed. Have you force refreshed your css? `ctrl+shift+f5` (win) or `cmd+shift+r` (mac).

**Comment by Kyrremann** [comment]
Side-note: check out `Augrek Brighthelm`, looks like there are too much information on that NPC/monster.

**Comment by Kyrremann** [comment]
I fixed the problem with the names, was using the file title, not the monster name. Also noticed that there still are som duplicate creatures.

**Comment by chisaipete** [comment]
Yeah, it needs some general pruning and sprucing up.  I like where this is going!  Let me clarify, I was hoping that we'd go back to a complementary green color on the site, I had found a color. Are you saying you had put it in?  I am seeing the color after pulling a rebuilding, so I'm assuming yes.

**Comment by Kyrremann** [comment]
> Yeah, it needs some general pruning and sprucing up. I like where this is going! Let me clarify, I was hoping that we'd go back to a complementary green color on the site, I had found a color. Are you saying you had put it in? I am seeing the color after pulling a rebuilding, so I'm assuming yes.

Ah, then I misunderstood. I went for the orange all over :p I'll switch to the green then!

**Comment by chisaipete** [comment]
> > Yeah, it needs some general pruning and sprucing up. I like where this is going! Let me clarify, I was hoping that we'd go back to a complementary green color on the site, I had found a color. Are you saying you had put it in? I am seeing the color after pulling a rebuilding, so I'm assuming yes.
> 
> Ah, then I misunderstood. I went for the orange all over :p I'll switch to the green then!

Yeah, I was meaning, just the site branding--I like how the stat block looks like the printed blocks, just an updated green color for the top line and other branding highlights.  The statblock is fine in vomity orange.  I just changed the brand-color-secondary to: $brand-color-secondary: #109269; Which yielded a pleasant contrasty color scheme.  Make sense?  (I'd add the change myself, but I don't know if I can push to your dev branch)

**Comment by Kyrremann** [comment]
It's a branch on my fork, so I don't think you can edit it. The last commit fixes the colour, and switches till your new green-ish-colour.

**Comment by Kyrremann** [comment]
Doh, I misunderstood again. You wanted the vomit-colour on the statblock, but wanted a new colour on the top line of the site?

I made this
image

but you want this:
image

**Comment by chisaipete** [comment]
> Doh, I misunderstood again. You wanted the vomit-colour on the statblock, but wanted a new colour on the top line of the site?
> 
> I made this
> image
> 
> but you want this:
> image

Yes, vomit on block, branding in complementary green, like this in main.scss:

$text-color:       #333;
$background-color: #fdfdfd;
$brand-color: #4D96B9;
**$brand-color-secondary: #109269;**
$brand-color-light: lighten($brand-color-secondary, 5%);
$brand-color-dark: darken($brand-color-secondary, 5%);

**Comment by chisaipete** [comment]
It's beautiful!  Thanks for all your hard work!  Unless you have more updates for this PR I'm going to go ahead and merge + close this. Awesome, awesome!

**Comment by chisaipete** [comment]
Gah! Typo in the footer:

image

**Comment by chisaipete** [comment]
I can fix that later if you are done with your changes :)

**Comment by Kyrremann** [comment]
I'm done with the changes. And good spotting.

**Pull request merged**
