### PR TITLE
Upgrade jekyll and other minor changes

### LINKED ISSUE #58: Upgrade Jekyll and use collections
I just started looking at this project, and I was wondering why you are building the project with Rake, and not just letting Github do the building automatically when you commit? 

Also, instead of using posts, latest Jekyll lets you add collections. This will save you the hassle with the date. Then you could either just use the monster name, or have an arbitrary number.

If you would like, I can make a PR request with a fix for both. One with the update and cleaned for latest Jekyll, and another PR with monsters as a collection.

### PR DESCRIPTION
**Pull request by Kyrremann**
Fixed #58 

Okay, I think I'm nearly finished. What's missing is the rest of the generic tag pages. I've used a new way to handle tags, so we don't have to generate `_site` every time we make a change. Now we only need to generate something each time we add a new creature with a new tag.

You can also stop using the extra `gh-pages` branch, as new Github fixes this behind the scenes.

- [ ] Script for generating missing tag-sites
- [x] Search-box on tag-sites

Hopefully you don't feel that I'm changing too much of your code. I've tried to keep it as close to the old one as possible, and just made it cleaner/simpler where I felt it was necessary. I may have gotten a bit overboard, but I think that the code is better and a bit more maintainable now.

### CODE REVIEW

**Comment by chisaipete** [comment]
Let me sit down an start reviewing before I give a full reaction.  But, the only things I'm going to be critical about is if the user experience degrades in any way.  If the site ends up being slower or the number of clicks to find a monster increases, I'll probably be pretty hesitant to accept.  That's my primary concern.  The point of the project was to have a lightning fast reference to get out of the way of Players at the table.  Assuming you've done an excellent job keeping that parity, then you should be good.  I'll be awaiting your final PR! 👍

**Comment by Kyrremann** [comment]
I totally agree about the speed or degrading the user experience! And you should feel in no way obliged to merge, if you don't feel like it is right :)

Forgot I'm going to a concert tonight, so the final commits are probably coming tomorrow instead.

**Comment by Kyrremann** [comment]
Note to self: Use generators to create missing tag-pages?
https://jekyllrb.com/docs/plugins/generators/

**Comment by Kyrremann** [comment]
Okay, I think I'm finally done? Except for the missing tag-generator. Plus, did you want the tag pages also to be sorted by name?

**Comment by Kyrremann** [comment]
One idea to solve the challenge rating stuff is to add `creature_name (cr??)` to the output of the title, then you could search for it instead. Type `cr14` and you will instantly see all creatures with challenge rating 14. Maybe we could even hide the `cr??`?

**Comment by chisaipete** [comment]
Sorry, I've been busy this weekend and haven't had a chance to take a look yet.  In order to test locally, do I need to do anything differently than I have before?  How does publishing change? Or am I conflating a different PR?

I'll try to take a look tomorrow!

**Comment by Kyrremann** [comment]
No worries.
I'll update the README with how to test locally and how to publish changes. It's simpler to add minor changes, but you need to create a new `_tags/file` if you need a new tag. Hopefully I'll manage to create a generator to solve the tags-problem. So that you can run `jekyll generate-tags` to simplify it.

But, yeah, to run locally, all you have to do is run `jekyll serve -i` `-i` is to make changes faster to load.

**Comment by chisaipete** [comment]
I've merged the other two PRs, the MTOF PR created a mix of posts which were dated and the rest not, I hope you can sort that out in this PR (I know that's asking a bit, otherwise, I can correct it: my thought was that this PR probably eliminates the need for a date anyway).

**Comment by Kyrremann** [comment]
There we go, updated the branch, and cleaned the files with dates.

**Comment by chisaipete** [comment]
Do I need to update Jekyll on my system to test?

**Comment by Kyrremann** [comment]
Hum, probably. `gem update jekyll` should be enough to get latest.

**Comment by chisaipete** [comment]
Hey this is pretty slick.  I only saw one issue so far:
image
I think there might be a few duplicate creatures...but that's not necessarily the fault of your PR :)

So, what are the cool features I should be looking at for this build?  Also, how do I release it on my gh pages?

**Comment by Kyrremann** [comment]
Doh, I'll take a loot at the duplicates. There where some others too, but I found those :p

Cool features? Hum, not that much really.
* you don't have to use the `gh-pages` branch any more. So any commit to master is published. (You need to update this in the repo settings on github before this works)
* no more posts, as we use collections (so dates are not necessary any more)
* no need for prerendering, github builds the page for you (see PS)
* you site has been updated to latest jekyll

PS: If we're adding a new tag, we need to create a new tag-page (see `_tags`). I have a simple manual solution for that (just need to code it done), and we can automate it with TravisCI or something similar

**Comment by Kyrremann** [comment]
Took another look a the duplicates, and noticed a lot of small mistakes. `title` should be changed to `name`, and `markdown` should be changed to `md` (uniformity).

**Comment by Kyrremann** [comment]
What should be do about this one?
```
$ diff amnizu.md amnizu_variant_.md
3c3
< name: "Amnizu"
---
> name: "Amnizu (variant)"
55c55,57
< ***Forgetfulness (Recharge 6)*** The amnizu targets one creature it can see within 60 feet of it. That creature must make a DC 18 Intelligence saving throw and on a failure the target is stunned for 1 minute. A stunned creature repeats the saving throw at the end of each of its turns, ending the effect on itself on a success. If the target remains stunned for the full minute, it forgets everything it sensed, experienced, and learned during the last 5 hours.
\ No newline at end of file
---
> ***Forgetfulness (Recharge 6)*** The amnizu targets one creature it can see within 60 feet of it. That creature must make a DC 18 Intelligence saving throw and on a failure the target is stunned for 1 minute. A stunned creature repeats the saving throw at the end of each of its turns, ending the effect on itself on a success. If the target remains stunned for the full minute, it forgets everything it sensed, experienced, and learned during the last 5 hours.
>
> ***Summon Devil (1/Day)*** The amnizu summons 2d4 bearded devils or 1d4 barbed devils. A summoned devil appears in an unoccupied space within 60 feet of the amnizu, acts as an ally of the amnizu, and can't summon other devils. It remains for 1 minute, until the amnizu dies, or until its summoner dismisses it as an action
\ No newline at end of file
```

The only difference is the extra action.

**Comment by Kyrremann** [comment]
The following files are duplicates, and I'm not sure which one is correct:
```
Abyssal Wretch
Air Elemental Myrmidon
Astral Dreadnought
Deathlock Wight
Derro Savant
Duergar Kavalrachni
Duergar Soulblade
Duergar Stone Guard
Duergar Xarrorn
Earth Elemental Myrmidon
Female Steeder
Fire Elemental Myrmidon
Fraz-Urb'luu
Githyanki Knight
Githyanki Warrior
Graz'zt
Male Steeder
Vampiric Mist
Water Elemental Myrmidon
```

Could you merge these?

**Comment by chisaipete** [comment]
> Could you merge these?

I'd be happy to tackle that

**Comment by Kyrremann** [comment]
If you like, you can just merge this branch in to master, and then fix the duplicates.
After that I'll make a PR for the statblock, and create the tag-generator.

**Comment by Kyrremann** [comment]
Maybe we should get a favicon too :D
https://game-icons.net/tags/creature.html

**Comment by chisaipete** [comment]
I'll need to take some time and sort out the gh-pages settings, but you should be ungated.  I'm thinking the Unicorn favicon might just be fantastic (but black on white not white on black).

**Comment by Kyrremann** [comment]
Cool. I'll create a PR for that.

**Comment by chisaipete** [comment]
Hey, thanks for all this fantastic work! I finally got it all merged in and the site switched over tonight.  I don't know what took me so long--but I love the fact that I don't have to build it and upload to the gh-pages branch anymore!  ⭐️ for you!

**Comment by Kyrremann** [comment]
Looking great, and glad to hear that you liked the changes!

**Pull request merged**
