### PR TITLE
Do not print header and footer

### PR DESCRIPTION
**Pull request by thisboyiscrazy**

### CODE REVIEW

**Comment by chisaipete** [comment]
Can you give  a bit more description on what the header and footer hiding is for?

**Comment by thisboyiscrazy** [comment]
When I print a page out (goblin for example) to use in my game, The
site-header and site-footer only take up space and serve no purpose.

**Comment by chisaipete** [comment]
Doesn't that functionally break the site though? There are no longer navigation buttons to get back to the main page, etc

**Comment by thisboyiscrazy** [comment]
It only applies to "print" (e.g. paper) media. Not screen.

It only hides when you print the page.

**Comment by chisaipete** [comment]
Oh okay, let me pull and test then 👍

**Comment by chisaipete** [comment]
Looks great, thanks for your work!

**Pull request merged**
